version: "3.8"

services:
  hikaruzs-discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hikaruzs-discord-bot
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    command: ["node", "./dist/main/index.js"]